### ISSUE TITLE
Not able to download jar using maven dependency and getting error No class found

### ISSUE THREAD

**Issue by kumarshorav11** [cdancy/jenkins-rest#71]
Hi,
I am trying to use this library. For this, I have included dependency in my maven project.
```
<dependency>
			<groupId>com.cdancy</groupId>
			<artifactId>jenkins-rest</artifactId>
			<version>0.0.14</version>
		</dependency>
```
However, I was getting missing artifact error. So I just saw in .m2 folder and found there is no jar.
Only 4 other files were there. So I downloaded JAR manually and added in class path.
Now, I added basic code that is given in READ.md. 
Then I am getting following error :
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/jclouds/apis/ApiMetadata
	at com.ks.App.main(App.java:13)
Caused by: java.lang.ClassNotFoundException: org.jclouds.apis.ApiMetadata
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 1 more

```

**Comment by tbouffard** [comment]
@kumarshorav11 can you provide the maven log when you get missing artifact error please?
Remember that `jenkins-rest` is not available on Maven Central but on JCenter as described in the README. See also: https://bintray.com/cdancy/java-libraries/jenkins-rest
This means you have to addapt your local Maven settings.xml or add the jcenter repository to your pom, or configure your Maven Repository Manager to proxy JCenter

About the `ClassNotFoundException`, this is because you only added the `jenkins-rest` jar to the classpath but apparently not its dependencies.

**Comment by cdancy** [comment]
Hmmm ... you shouldn't _need_ to add dependencies as that should be taken care of for you. In either event I would definitely try to resolve things from bintray in the old way and see where that gets you.

**Comment by shubhashi88** [comment]
Hi all, Same issue I am getting while running the normal java application in my project. 
Exception in thread "main" java.lang.NoClassDefFoundError: org/jclouds/apis/ApiMetadata
Caused by: java.lang.ClassNotFoundException: org.jclouds.apis.ApiMetadata
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 1 more

The error occurred when we are trying to call the below method with valid parameters.
  JenkinsClient client = JenkinsClient.builder().endPoint(jenkinsServer).build();

Please note that we are using latest version of jenkins rest Jar -jenkins-rest-0.0.22.jar... 
It is not able to load the org.jclouds.apis.ApiMetadata class internally. 
Can you please help us to resolve this.

**Comment by cdancy** [comment]
@shubhashi88 are you using the `all` classifier? If so you may be on to something as it looks like the latest release does not have the relevant jclouds classes which is odd. Poking around now. However ... if you're using the standard GAV coordinates the jclouds dependencies should be pulled onto your classpath unless you're excluding them for some reason.

**Comment by cdancy** [comment]
@shubhashi88 I lied ... they are in fact in place just not in the spot mentioned by your comment. Do you have other version of jclouds on your classpath? Can you provide a reproducible snippet? Just gave things a go here and all worked as expected.

**Comment by shubhashi88** [comment]
@cdancy I have tried with jenkins-rest and version 12  and  with the below dependency in pom.xml
<dependency>
			<groupId>com.cdancy</groupId>
			<artifactId>jenkins-rest</artifactId>
			<version>0.0.12</version>
		</dependency>
and so while building the workspace I got below error 
Could not resolve dependencies for project test:jar:1.0-SNAPSHOT: Could not find artifact com.cdancy:jenkins-rest:jar:0.0.12 in maven2-repository.dev.java.net (http://download.java.net/maven/2/) -> [Help 1]

and later I downloaded latest version of jar from git hub and updated from below configuaration in POM
<dependency>
			<groupId>jenkins-rest</groupId>
			<artifactId>jenkins-rest</artifactId>
			<version>0.0.22</version>
			<scope>system</scope>
			<systemPath>${basedir}\libs\jenkins-rest-0.0.22.jar</systemPath>
		</dependency>
After that build was successful but while running below code

 public static void main(String[] args) throws Exception {

        String buildNumber = "", env = "", link = "";
         String jenkinsServer ="JenkinsServerURL" 
        String jenkinsJob = "Job URL";
 
        JenkinsClient client = JenkinsClient.builder().endPoint(jenkinsServer).build(); // in this line of code it is throwing below mentioned run time exception

} 
Exception in thread "main" java.lang.NoClassDefFoundError: org/jclouds/apis/ApiMetadata

**Comment by cdancy** [comment]
@shubhashi88 I personally do NOT publish this jar to maven ... I ONLY publish it to bintray. So if you're getting something from maven that might be your first clue. As far as the single jar is concerned: that won't work on its own as you **need** all the other jclouds dependencies. The only way you can get around this is by downloading the `-all` version which has all dependencies baked in ... OR ... use a proper dependency management tool (i.e. gradle or maven) to resolve this library and all its dependencies for you.

**Comment by tbouffard** [comment]
@shubhashi88 according to your maven logs, maven is unable to find the lib, probably because your local maven installation is not aware of the JCenter repository (or you use a corporate repository manager not aware of it)

Please add the JCenter repository to your pom.xml or local settings.xml with something like in the following
Resources: https://maven.apache.org/guides/introduction/introduction-to-repositories.html

```xml
<repositories>
    <repository>
      <id>jcenter</id>
      <url>https://jcenter.bintray.com/</url>
    </repository>
</repositories>
```

**Comment by shubhashi88** [comment]
@tbouffard  : -  I have tried with adding the jcenter repository in POM but again it is unable to install the dependency. It is again throwing error.
 

![image](https://user-images.githubusercontent.com/35379011/72717210-9ab7e700-3b99-11ea-9a7f-eb0fc7146e43.png)

**Comment by tbouffard** [comment]
@shubhashi88 
according to the maven error log, the groupId of the jenkins-rest dependency seems wrong: you are using `jenkins-rest` and the README states to use `com.cdancy`
I suggest you to declare the jenkins-rest dependency in your pom.xml file as in the following
```xml
<dependency>
  <groupId>com.cdancy</groupId>
  <artifactId>jenkins-rest</artifactId>
  <version>0.0.22</version>
</dependency>
```

**Comment by cdancy** [comment]
Closing issue. Feel free to re-open if you'd like to discuss further.

**Comment by shanmukakondaveti** [comment]
hii,i tried com.cdancy.jenkind jar in our project,it is working fine in local application ,but when we run it as jenkins job ,application is failing as this jar is not importing from pom.xml,everything looks fine in local,but what wrong with jenkins pipeline is not understanding?can anyobody solve my issue
![image (3)](https://user-images.githubusercontent.com/83701275/127851341-46b0830f-9c7b-4a54-b3d7-9a1a13e2ea10.png)
