### ISSUE TITLE
Support JDK17

### ISSUE THREAD

**Issue by choweiyuan** [cdancy/jenkins-rest#253]
### Expected Behavior
I'd like some confidence that this library supports JDK17

### Current Behavior
Unclear if this supports. but based on travis.yml we seem to have removed running against JDK17 due to some library incompatibility.
https://github.com/cdancy/jenkins-rest/commit/737a770adb675818cc3988a4e33aa5230136dc7c

### Context
I'm considering to upgrade Spring Boot 3 when its ready, and Spring Boot 3 will not support  < JDK17. 
https://spring.io/blog/2022/05/24/preparing-for-spring-boot-3-0

So it'll be key to have this library ready for JDK17

**Comment by cdancy** [comment]
@choweiyuan that was due to a plugin related reason for the build itself and not anything to do with jdk17. Things should just work unless anyone has spotted a reason it doesn't.

**Comment by fatihhguvenn** [comment]
Below initialization fails with Spring Boot 2.7.x
JenkinsClient.builder().endPoint(jenkinsHost).credentials(jenkinsUser:jenkinsToken).build();

Works well with 2.6.x though

**Comment by martinda** [comment]
@fatihhguvenn can you share the exact error message and a small example of how to reproduce?

**Comment by fatihhguvenn** [comment]
@martinda here is an example project 
[jenkinsExc.zip](https://github.com/cdancy/jenkins-rest/files/9679545/jenkinsExc.zip)

- It's a gradle project and needs to be built before run.
- It's a Spring Boot project and src\main\java\com\je\jenkinsExc\JenkinsExcApplication.java should be run
- JenkinsClient needs static String fields to be set properly in src\main\java\com\je\jenkinsExc\JenkinsService.java

When it is run Exception is thrown from JenkinsClient

**Comment by jakubriegel** [comment]
@cdancy any developments here?

**Comment by kevin-uslu** [comment]
I also get an error when instanticiating a JenkinsClient.

I am using :

Java : 17
Sprng Boot : 2.7.11
Jenkins Server : 2.401 (same with 2.400)
Jenkins Rest : 1.0.2

Code :

```
JenkinsClient client = JenkinsClient.builder()
                .endPoint("${JENKINS_URL}")
                .credentials("${username}:${password}")
                .build();

SystemInfo systemInfo = client.api().systemApi().systemInfo();
```

Exception :

```
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) [Guice/ErrorInCustomProvider]: NoSuchMethodError: com/google/gson/internal/ConstructorConstructor
```

Full stack trace enclosed.

Any help is appreciated.
Thanks in advance.

[JenkinsClientException.log](https://github.com/cdancy/jenkins-rest/files/11319284/JenkinsClientException.log)

**Comment by kevin-uslu** [comment]
The issue is no longer reproduced when the dependency is declared with "all" classifier as suggested by cdancy on another issue.

```
<dependency>
	<groupId>io.github.cdancy</groupId>
	<artifactId>jenkins-rest</artifactId>
	<version>1.0.2</version>
	<classifier>all</classifier>
</dependency>
```

**Comment by cdancy** [comment]
@kevin-uslu that is correct path forward here. Recent JDK releases change things a bit and so to get around that you really need to use the `all` classifier with is just an uber-jar with all dependencies baked in.
